services:
  # 1. The Backend API
  - type: web
    name: ecommerce-backend
    runtime: docker
    repo: https://github.com/GobirajM2003/ecommerce-microservices
    rootDir: backend
    plan: free
    envVars:
      - key: PORT
        value: 5000

  # 2. The Frontend Store
  - type: web
    name: ecommerce-frontend
    runtime: docker
    repo: https://github.com/GobirajM2003/ecommerce-microservices
    rootDir: frontend
    plan: free